# Generated by Django 5.1.5 on 2026-04-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAccessStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('access_type', models.CharField(choices=[('wayback', 'wayback'), ('ia_file', 'ia_file')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='ftsearch_dailyaccessstat_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'access_type'), name='ftsearch_dailyaccessstat_date_type_uniq')],
            },
        ),
    ]
