# Generated by Django 5.1.5 on 2026-04-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyaccessstat',
            name='ftsearch_dailyaccessstat_date_type_uniq',
        ),
        migrations.AddField(
            model_name='dailyaccessstat',
            name='referrer_bucket',
            field=models.CharField(choices=[('direct', 'direct'), ('google_scholar', 'google_scholar'), ('google', 'google'), ('other', 'other')], default='direct', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='dailyaccessstat',
            constraint=models.UniqueConstraint(fields=('date', 'access_type', 'referrer_bucket'), name='ftsearch_dailyaccessstat_date_type_ref_uniq'),
        ),
    ]
