[project]
name = "djscholar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nate smith", email = "nsmith@archive.org" }
]
requires-python = ">=3.13"
dependencies = [
    "django==5.1.5",
    "elasticsearch==7.13.4",
    "django-ninja==1.4.0",
    "gevent==25.5.1",
    "gunicorn>=23.0",
    "ninja-api-key==1.0.2",
    "psycopg[binary]==3.2.4",
    "python-dateutil==2.9.*",
    "sentry-sdk==2.30",
    "surt==0.3.1",
    "jinja2==3.1.6",
    "pygal==3.1.0",
    "citeproc-py==0.9.0",
    "citeproc-py-styles==0.1.5",
]

[project.scripts]
djscholar = "djscholar:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/djscholar"]

[[tool.uv.index]]
url = "https://nexus.us.archive.org/repository/pypi-group/simple"
default = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "djscholar.site.settings.base"

#[tool.pylsp-mypy]
## Sadly, this would not acknowledge mypy_django_plugin
#enabled = true
#dmypy = true
#live_mode = false
#strict = false
#exclude = ["tests/*"]

[tool.django-stubs]
django_settings_module = "djscholar.site.settings.base"


[dependency-groups]
dev = [
    "django-stubs[compatible-mypy]==5.1.2",
    "factory-boy==3.3.3",
    "mypy==1.14.1",
    "pytest-django==4.11.0",
    "ruff==0.13.1",
    "ty>=0.0.12",
]
