stages:
  - test
  - build
  - upload
variables:
  GO_VERSION: 1.25.6-trixie

build:trawler-build:
  stage: build
  image: golang:${GO_VERSION}
  rules:
    - if: $CI_COMMIT_TAG =~ /^trawler-\d+\.\d+\.\d+.$/
  script:
    - cd trawler
    - make test
    - make trawler
  artifacts:
    paths:
      - "trawler"
    expire_in: 1 week

test:trawler-mr-test:
  stage: test
  image: golang:${GO_VERSION}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - cd trawler
    - make test

upload:trawler-upload:
  stage: upload
  image: curlimages/curl:8.18.0
  rules:
    - if: $CI_COMMIT_TAG =~ /^trawler-\d+\.\d+\.\d+.$/
  dependencies:
    - build:trawler-build
  script:
    - export VERSION=$(./trawler version)
    - echo "Uploading trawler binary to nexus..."
    - cd trawler
    - |
      curl -v --user "$NEXUS_ADS_GLCI_PUBLISHER_USERNAME:$NEXUS_ADS_GLCI_PUBLISHER_PASSWORD" \
        --upload-file trawler "${NEXUS_URL}/repository/raw-internal/scholar/trawler-${VERSION}"

build-grobid:
  image: gradle:jre11-slim
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never
  variables:
    BUILD_DIR: ia_grobid_build
    GROBID_VERSION: 0.8.2
    GROBID_REPO: https://github.com/kermitt2/grobid.git
    NEXUS_URL: http://nexus.us.archive.org
    NEXUS_BASICAUTH: "$NEXUS_USER:$NEXUS_PASSWORD"
  script:
    - mkdir $BUILD_DIR
    - git clone --branch $GROBID_VERSION --single-branch $GROBID_REPO
    - cd grobid
    - chmod +x gradlew
    - ./gradlew assemble
    - mv grobid-service/build/distributions/*.zip ../$BUILD_DIR
    - mv grobid-home/build/distributions/*.zip ../$BUILD_DIR
    - cd ..
    - rm -fr grobid
    - curl --user $NEXUS_BASICAUTH --upload-file $BUILD_DIR/grobid-home-$GROBID-VERSION.zip $NEXUS_URL/repository/raw-internal/grobid/grobid-home-$GROBID-VERSION.zip
    - curl --user $NEXUS_BASICAUTH --upload-file $BUILD_DIR/grobid-service-$GROBID-VERSION.zip $NEXUS_URL/repository/raw-internal/grobid/grobid-service-$GROBID-VERSION.zip
