#!/bin/env bash

# this file creates several large .tsv files from a fatcat database intended for consumption into the new database schema
# make sure you have about a TB to work with if you're running this.

SOURCE="legacy_import"
PSQL="psql -D fatcat_pod"
CONTAINERS_OUT="containers.tsv"
CREATORS_OUT="creators.tsv"
WORKS_OUT="works.tsv"
RELEASES_OUT="releases.tsv"
RELEASES_EXTID_OUT="releaseextids.tsv"
RELEASES_ABSTRACT_OUT="releaseabstracts.tsv"
RELEASES_CONTRIB_OUT="releasecontribs.tsv"
RELEASES_REF_OUT="releaserefs.tsv"
FILES_OUT="files.tsv"
FILES_URL_OUT="fileurls.tsv"
FILESETS_OUT="fileurls.tsv"
FILESETS_URL_OUT="fileseturls.tsv"
FILESETS_FILE_OUT="filesetfiles.tsv"
WEBCAPTURES_OUT="webcaptures.tsv"
WEBCAPTURES_URL_OUT="webcaptureurls.tsv"
WEBCAPTURES_CDX_OUT="webcapturecdx.tsv"

dump_containers() {
  echo "dumping containers to $CONTAINERS_OUT"
  cat << EOF | $PSQL
\copy (
  SELECT
    ci.id AS legacy_ident,
    cr.name,
    to_json(cr.extra_json) AS extra,
    cr.container_type,
    cr.publisher,
    cr.issnl,
    cr.issne,
    cr.issnp,
    cr.wikidata_qid,
    '$SOURCE' AS source
  FROM container_ident ci
  JOIN container_rev cr ON ci.rev_id = cr.id
  WHERE
    ci.is_live = true
    AND
    ci.redirect_id is NULL
    AND
    cr.container_type != 'test'
  ) TO '$CONTAINERS_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

dump_creators() {
  echo "dumping creators to $CREATORS_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  ci.id AS legacy_ident,
  cr.display_name,
  cr.given_name,
  cr.surname,
  cr.orcid,
  '$SOURCE' AS source,
  to_json(cr.extra_json) AS extra
FROM creator_ident ci
JOIN creator_rev cr ON ci.rev_id = cr.id
WHERE
  ci.is_live = true
  AND
  ci.redirect_id IS NULL
) TO '$CREATORS_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

dump_works() {
  echo "dumping works to $WORKS_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  wi.id AS legacy_ident,
  '$SOURCE' AS source,
  to_json(wr.extra_json) AS extra
FROM work_ident wi
JOIN work_rev wr ON wi.rev_id = wr.id
WHERE
  wi.is_live = true
AND
  wi.redirect_id IS NULL
) TO '$WORKS_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

dump_releases() {
  echo "dumping releases to $RELEASES_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  ri.id AS legacy_ident,
  rr.id AS legacy_rev,
  
  to_json(rr.extra_json) AS extra,
  '$SOURCE' AS source,
  rr.title,
  rr.original_title,
  rr.subtitle,
  rr.release_type,
  rr.release_stage,
  rr.release_date,
  rr.release_year,
  rr.volume,
  rr.issue,
  rr.pages,
  rr.number,
  rr.version,
  rr.publisher,
  rr.language,
  rr.license_slug,
  rr.withdrawn_status,
  
  rr.work_ident_id AS legacy_work_ident,
  rr.container_ident_id AS legacy_container_ident,
  rr.doi as legacy_doi,
  rr.pmid as legacy_pmid,
  rr.pmcid as legacy_pmcid,
  rr.wikidata_qid as legacy_wikidata_qid,
  rr.core_id as legacy_core_id,
  
  (SELECT to_json(refs_json) 
   FROM refs_blob rb 
   WHERE rb.sha1 = rr.refs_blob_sha1) AS refs
FROM
  release_ident ri
JOIN release_rev rr ON ri.rev_id = rr.id
WHERE ri.is_live = true
AND ri.redirect_id IS NULL
) TO '$RELEASES_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

dump_releaseextid() {
  echo "dumping release external IDs to $RELEASES_EXT_ID_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  ei.release_rev AS legacy_release_rev,
  ei.extid_type AS id_type,
  ei.value AS id_value
FROM release_ident ri
JOIN release_rev_extid ei ON ri.rev_id = ri.release_rev
WHERE ri.is_live = true
AND ri.redirect_id IS NULL
) TO '$RELEASES_EXT_ID_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

#Table "public.fcapi_releaseabstract"
#    Column    |         Type          | Collation | Nullable |             Default
#--------------+-----------------------+-----------+----------+----------------------------------
# id           | bigint                |           | not null | generated by default as identity
# mimetype     | character varying     |           | not null |
# sha1         | character varying(40) |           | not null |
# content      | text                  |           | not null |
# release_id   | bigint                |           | not null |
# language     | character varying(2)  |           |          |
# license_slug | character varying     |           |          |
#
#                               Table "public.release_rev_abstract"
#    Column     |  Type  | Collation | Nullable |                     Default
#---------------+--------+-----------+----------+--------------------------------------------------
# id            | bigint |           | not null | nextval('release_rev_abstract_id_seq'::regclass)
# release_rev   | uuid   |           | not null |
# abstract_sha1 | text   |           | not null |
# mimetype      | text   |           |          |
# lang          | text   |           |          |
#
#       Table "public.abstracts"
# Column  | Type | Collation | Nullable | Default
#---------+------+-----------+----------+---------
# sha1    | text |           | not null |
# content | text |           | not null |


dump_releaseabstract() {
  echo "dumping release abstracts to $RELEASES_ABSTRACT_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  ra.release_rev AS legacy_release_rev,
  ra.abstract_sha1 AS sha1,
  ra.mimetype,
  ra.lang AS language,
  (SELECT content
   FROM abstracts a
   WHERE ra.abstract_sha1 = a.sha1)
FROM release_ident ri
JOIN release_rev_abstract ra ON ri.rev_id = ra.release_rev
WHERE ri.is_live = true
AND ri.redirect_id IS NULL
) TO '$RELEASES_ABSTRACT_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

#Table "public.release_contrib"
#      Column      |  Type   | Collation | Nullable |                   Default
#------------------+---------+-----------+----------+---------------------------------------------
# id               | bigint  |           | not null | nextval('release_contrib_id_seq'::regclass)
# release_rev      | uuid    |           | not null |
# creator_ident_id | uuid    |           |          |
# raw_name         | text    |           |          |
# role             | text    |           |          |
# raw_affiliation  | text    |           |          |
# index_val        | integer |           |          |
# extra_json       | jsonb   |           |          |
# given_name       | text    |           |          |
# surname          | text    |           |          |
#
#Table "public.fcapi_releasecontrib"
#     Column      |       Type        | Collation | Nullable |             Default
#-----------------+-------------------+-----------+----------+----------------------------------
# id              | bigint            |           | not null | generated by default as identity
# raw_name        | character varying |           | not null |
# given_name      | character varying |           |          |
# surname         | character varying |           |          |
# role            | character varying |           |          |
# raw_affiliation | character varying |           |          |
# index_val       | smallint          |           | not null |
# extra           | jsonb             |           | not null |
# creator_id      | bigint            |           | not null |
# release_id      | bigint            |           | not null |

dump_releasecontrib() {
  echo "dumping release contribs to $RELEASES_CONTRIB_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  rc.release_rev AS legacy_release_rev,
  rc.raw_name,
  rc.given_name,
  rc.surname,
  rc.creator_ident_id AS legacy_creator_ident,
  rc.role,
  rc.raw_affiliation,
  rc.index_val AS position,
  to_json(rc.extra_json) AS extra,
FROM release_ident ri
JOIN release_contrib rc ON ri.rev_id = rc.release_rev
WHERE ri.is_live = true
AND ri.redirect_id IS NULL
) TO '$RELEASES_ABSTRACT_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

#        Table "public.fcapi_releaseref"
#      Column       |   Type   | Collation | Nullable |             Default
#-------------------+----------+-----------+----------+----------------------------------
# id                | bigint   |           | not null | generated by default as identity
# position          | smallint |           | not null |
# release_id        | bigint   |           | not null |
# target_release_id | bigint   |           | not null |

# Table "public.release_ref"
#         Column          |  Type   | Collation | Nullable | Default
#-------------------------+---------+-----------+----------+---------
# release_rev             | uuid    |           | not null |
# index_val               | integer |           | not null |
# target_release_ident_id | uuid    |           | not null |

dump_releaseref() {
  echo "dumping release refs to $RELEASES_REF_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  rr.index_val AS position,
  rr.release_rev AS legacy_release_rev,
  rr.target_release_ident_id AS legacy_target_release_ident
FROM release_ident ri
JOIN release_ref rr ON ri.rev_id = rr.release_rev
WHERE ri.is_live = true
AND ri.redirect_id IS NULL
) TO '$RELEASES_REF_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

# Table "public.file_rev"
#    Column     |  Type  | Collation | Nullable |      Default
#---------------+--------+-----------+----------+--------------------
# id            | uuid   |           | not null | uuid_generate_v4()
# extra_json    | jsonb  |           |          |
# size_bytes    | bigint |           |          |
# sha1          | text   |           |          |
# sha256        | text   |           |          |
# md5           | text   |           |          |
# mimetype      | text   |           |          |
# content_scope | text   |           |          |
#
#
# Table "public.fcapi_releasefile"
#    Column     |           Type           | Collation | Nullable |             Default
#---------------+--------------------------+-----------+----------+----------------------------------
# id            | bigint                   |           | not null | generated by default as identity
# created       | timestamp with time zone |           | not null | statement_timestamp()
# updated       | timestamp with time zone |           | not null | statement_timestamp()
# source        | character varying        |           | not null |
# hidden_reason | text                     |           |          |
# extra         | jsonb                    |           |          |
# size_bytes    | bigint                   |           | not null |
# sha1          | character varying(40)    |           | not null |
# sha256        | character varying(64)    |           | not null |
# md5           | character varying(32)    |           | not null |
# mimetype      | character varying        |           | not null |
# release_id    | bigint                   |           | not null |
# hidden_when   | timestamp with time zone |           |          |
# legacy_rev    | uuid                     |           | not null |

dump_file() {
  echo "dumping files to $FILES_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  fi.rev_id AS legacy_rev,
  fi.id AS legacy_ident,
  '$SOURCE' as source,
  fr.size_bytes,
  fr.sha1,
  fr.sha256,
  fr.mimetype,
  fr.md5,
  to_json(f.extra_json) AS extra,
  (SELECT target_release_ident_id
   FROM file_rev_release frr
   WHERE frr.file_rev = fr.id
  ) AS legacy_release_ident
FROM
  file_ident fi
JOIN file_rev fr ON fi.rev_id = fr.id
WHERE fi.is_live = true
AND fi.redirect_id IS NULL
) TO '$RELEASES_REF_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

#          Table "public.file_rev_url"
#  Column  |  Type  | Collation | Nullable |                 Default
#----------+--------+-----------+----------+------------------------------------------
# id       | bigint |           | not null | nextval('file_rev_url_id_seq'::regclass)
# file_rev | uuid   |           | not null |
# rel      | text   |           | not null |
# url      | text   |           | not null |

# Table "public.fcapi_fileurl"
# Column  |           Type            | Collation | Nullable |             Default
#---------+---------------------------+-----------+----------+----------------------------------
# id      | bigint                    |           | not null | generated by default as identity
# rel     | character varying         |           | not null |
# url     | character varying(100000) |           | not null |
# file_id | bigint                    |           | not null |


dump_fileurl() {
  echo "dumping files to $FILES_URL_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  fu.rel,
  fu.url,
  fi.rev_id AS legacy_file_rev
FROM
  file_ident fi
JOIN file_rev_url fu ON fi.rev_id = fu.file_rev
WHERE fi.is_live = true
AND fi.redirect_id IS NULL
) TO '$FILES_URL_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

# Table "public.fcapi_fileset"
#    Column     |           Type           | Collation | Nullable |             Default
#---------------+--------------------------+-----------+----------+----------------------------------
# id            | bigint                   |           | not null | generated by default as identity
# created       | timestamp with time zone |           | not null | statement_timestamp()
# updated       | timestamp with time zone |           | not null | statement_timestamp()
# source        | character varying        |           | not null |
# hidden_reason | text                     |           |          |
# extra         | jsonb                    |           |          |
# release_id    | bigint                   |           | not null |
# hidden_when   | timestamp with time zone |           |          |
# legacy_rev    | uuid                     |           | not null |
#  Table "public.fileset_rev"
#    Column     | Type  | Collation | Nullable |      Default
#---------------+-------+-----------+----------+--------------------
# id            | uuid  |           | not null | uuid_generate_v4()
# extra_json    | jsonb |           |          |
# content_scope | text  |           |          |
#
#          Table "public.fileset_rev_release"
#         Column          | Type | Collation | Nullable | Default
#-------------------------+------+-----------+----------+---------
# fileset_rev             | uuid |           | not null |
# target_release_ident_id | uuid |           | not null |


dump_fileset() {
  echo "dumping filesets to $FILESETS_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  fi.rev_id AS legacy_rev,
  to_json(f.extra_json) AS extra,
  '$SOURCE' AS source,
  (SELECT
    target_release_ident_id
   FROM fileset_rev_release frr
   WHERE frr.fileset_rev = fi.rev_id
  ) AS legacy_release_ident
FROM
  fileset_ident fi
JOIN fileset_rev fr ON fi.rev_id = fr.id
WHERE fi.is_live = true
AND fi.redirect_id IS NULL
) TO '$FILESETS_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

dump_fileseturls() {
  echo "dumping fileset urls to $FILESETS_URL_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  fi.rev_id AS legacy_fileset_rev,
  fu.rel,
  fu.url
FROM
  fileset_ident fi
JOIN fileset_rev_url fu ON fi.rev_id = fu.fileset_rev
WHERE fi.is_live = true
AND fi.redirect_id IS NULL
) TO '$FILESETS_URL_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

# Table "public.fcapi_filesetfile"
#    Column     |           Type           | Collation | Nullable |             Default
#---------------+--------------------------+-----------+----------+-----------------------------
# id            | bigint                   |           | not null | generated by default as identity
# created       | timestamp with time zone |           | not null | statement_timestamp()
# updated       | timestamp with time zone |           | not null | statement_timestamp()
# source        | character varying        |           | not null |
# hidden_reason | text                     |           |          |
# extra         | jsonb                    |           |          |
# size_bytes    | bigint                   |           | not null |
# sha1          | character varying(40)    |           | not null |
# sha256        | character varying(64)    |           | not null |
# md5           | character varying(32)    |           | not null |
# mimetype      | character varying        |           | not null |
# fileset_id    | bigint                   |           | not null |
# hidden_when   | timestamp with time zone |           |          |
#
# Table "public.fileset_rev_file"
#   Column    |  Type  | Collation | Nullable |                   Default
#-------------+--------+-----------+----------+---------------------------------------------
# id          | bigint |           | not null | nextval('fileset_rev_file_id_seq'::regclass)
# fileset_rev | uuid   |           | not null |
# path_name   | text   |           | not null |
# size_bytes  | bigint |           | not null |
# md5         | text   |           |          |
# sha1        | text   |           |          |
# sha256      | text   |           |          |
# extra_json  | jsonb  |           |          |
# mimetype    | text   |           |          |

dump_filesetfiles() {
  echo "dumping fileset urls to $FILESETS_FILE_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  fi.rev_id AS legacy_fileset_rev,
  ff.path_name,
  '$SOURCE' AS source,
  ff.size_bytes,
  ff.md5,
  ff.sha1,
  ff.sha256,
  ff.mimetype,
  to_json(ff.extra_json) AS extra,
FROM
  fileset_ident fi
JOIN fileset_rev_file ff ON fi.rev_id = ff.fileset_rev
WHERE fi.is_live = true
AND fi.redirect_id IS NULL
) TO '$FILESETS_FILE_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

# Table "public.webcapture_rev"
#    Column     |           Type           | Collation | Nullable |      Default
#---------------+--------------------------+-----------+----------+--------------------
# id            | uuid                     |           | not null | uuid_generate_v4()
# extra_json    | jsonb                    |           |          |
# original_url  | text                     |           | not null |
# timestamp     | timestamp with time zone |           | not null |
# content_scope | text                     |           |          |
#          Table "public.fcapi_webcapture"
#    Column     |           Type            | Collation | Nullable |             Default
#---------------+---------------------------+-----------+----------+----------------------------------
# id            | bigint                    |           | not null | generated by default as identity
# created       | timestamp with time zone  |           | not null | statement_timestamp()
# updated       | timestamp with time zone  |           | not null | statement_timestamp()
# source        | character varying         |           | not null |
# hidden_reason | text                      |           |          |
# extra         | jsonb                     |           |          |
# original_url  | character varying(100000) |           | not null |
# release_id    | bigint                    |           | not null |
# captured      | timestamp with time zone  |           | not null |
# hidden_when   | timestamp with time zone  |           |          |
# legacy_rev    | uuid                      |           | not null |



dump_webcaptures() {
  echo "dumping webcaptures to $WEBCAPTURES_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  wi.rev_id AS legacy_rev,
  wi.id AS legacy_ident,
  '$SOURCE' AS source,
  to_json(wr.extra_json) AS extra,
  wr.original_url,
  wr.timestamp AS captured,
  (SELECT target_release_ident_id
   FROM webcapture_rev_release
   WHERE webcapture_rev = wr.id) AS legacy_release_id
FROM webcapture_ident wi
JOIN webcapture_rev wr ON wi.rev_id = wr.id
WHERE wi.is_live = true
AND wi.redirect_id IS NULL
) TO '$WEBCAPTURES_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

dump_webcapture_urls() {
  echo "dumping webcapture urls to $WEBCAPTURES_URL_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  wu.webcapture_rev AS legacy_webcapture_rev,
  wu.rel,
  wu.url
FROM webcapture_ident wi
JOIN webcapture_rev_url wu ON wu.webcapture_rev = wi.rev_id
WHERE wi.is_live = true
AND wi.redirect_id IS NULL
) TO '$WEBCAPTURES_URL_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}

#Table "public.fcapi_webcapturecdx"
#    Column     |           Type            | Collation | Nullable |             Default
#---------------+---------------------------+-----------+----------+----------------------------------
# id            | bigint                    |           | not null | generated by default as identity
# surt          | text                      |           | not null |
# url           | character varying(100000) |           | not null |
# mimetype      | character varying         |           | not null |
# status_code   | smallint                  |           | not null |
# sha1          | character varying(40)     |           | not null |
# sha256        | character varying(64)     |           | not null |
# size_bytes    | bigint                    |           | not null |
# webcapture_id | bigint                    |           | not null |
# captured      | timestamp with time zone  |           | not null |
#                                         Table "public.webcapture_rev_cdx"
#     Column     |           Type           | Collation | Nullable |                    Default
#----------------+--------------------------+-----------+----------+------------------------------------------------
# id             | bigint                   |           | not null | nextval('webcapture_rev_cdx_id_seq'::regclass)
# webcapture_rev | uuid                     |           | not null |
# surt           | text                     |           | not null |
# timestamp      | timestamp with time zone |           | not null |
# url            | text                     |           | not null |
# mimetype       | text                     |           |          |
# status_code    | bigint                   |           |          |
# sha1           | text                     |           | not null |
# sha256         | text                     |           |          |
# size_bytes     | bigint                   |           |          |

dump_webcapture_cdx() {
  echo "dumping webcapture cdx to $WEBCAPTURES_CDX_OUT"
  cat << EOF | $PSQL
\copy (
SELECT
  wc.webcapture_rev AS legacy_webcapture_rev,
  wc.surt,
  wc.url,
  wc.timestamp AS captured,
  wc.url,
  wc.mimetype,
  wc.status_code,
  wc.sha1,
  wc.sha256,
  wc.size_bytes
FROM webcapture_ident wi
JOIN webcapture_rev_cdx wc ON wc.webcapture_rev = wi.rev_id
WHERE wi.is_live = true
AND wi.redirect_id IS NULL
) TO '$WEBCAPTURES_CDX_OUT' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
EOF
}
