[project]
name = "scholstats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "httpx>=0.28",
  "pandas>=2.3",
  "httpx-retries>=0.4",
  "jinja2>=3.1.6",
] 

[[tool.uv.index]]
url = "http://nexus.us.archive.org/repository/pypi-group/simple"
default = true

[dependency-groups]
dev = [
    "matplotlib>=3.10.3",
    "seaborn>=0.13.2",
]

