# Generated by Django 5.1.5 on 2025-01-31 20:13

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('source', models.CharField(db_index=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.TextField()),
                ('extra', models.JSONField()),
                ('name', models.CharField()),
                ('container_type', models.CharField()),
                ('publisher', models.CharField()),
                ('issnl', models.CharField(db_index=True)),
                ('issne', models.CharField(db_index=True)),
                ('issnp', models.CharField(db_index=True)),
                ('wikidata_qid', models.CharField(db_index=True)),
                ('publication_status', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('source', models.CharField(db_index=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.TextField()),
                ('extra', models.JSONField()),
                ('display_name', models.CharField()),
                ('given_name', models.CharField()),
                ('surname', models.CharField()),
                ('orcid', models.CharField(db_index=True)),
                ('wikidata_qid', models.CharField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fileset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('source', models.CharField(db_index=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.TextField()),
                ('extra', models.JSONField()),
                ('content_scope', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('source', models.CharField(db_index=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.TextField()),
                ('extra', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilesetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('source', models.CharField(db_index=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.TextField()),
                ('extra', models.JSONField()),
                ('size_bytes', models.BigIntegerField()),
                ('sha1', models.CharField(max_length=40)),
                ('sha256', models.CharField(max_length=64)),
                ('md5', models.CharField(max_length=32)),
                ('mimetype', models.CharField()),
                ('fileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.fileset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('source', models.CharField(db_index=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.TextField()),
                ('extra', models.JSONField()),
                ('title', models.CharField()),
                ('original_title', models.CharField()),
                ('subtitle', models.CharField()),
                ('release_type', models.CharField()),
                ('release_stage', models.CharField()),
                ('release_date', models.DateField(null=True)),
                ('release_year', models.SmallIntegerField(null=True)),
                ('volume', models.CharField()),
                ('issue', models.CharField()),
                ('pages', models.CharField()),
                ('publisher', models.CharField()),
                ('language', models.CharField()),
                ('license_slug', models.CharField()),
                ('number', models.CharField()),
                ('version', models.CharField()),
                ('withdrawn_status', models.CharField()),
                ('withdrawn_date', models.DateField(null=True)),
                ('withdrawn_year', models.SmallIntegerField(null=True)),
                ('refs', models.JSONField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.container')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.work')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fileset',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release'),
        ),
        migrations.CreateModel(
            name='ReleaseAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimetype', models.CharField()),
                ('lang', models.CharField()),
                ('sha1', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseContrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField()),
                ('given_name', models.CharField()),
                ('surname', models.CharField()),
                ('role', models.CharField()),
                ('raw_affiliation', models.CharField()),
                ('index_val', models.SmallIntegerField()),
                ('extra', models.JSONField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.creator')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('source', models.CharField(db_index=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.TextField()),
                ('extra', models.JSONField()),
                ('size_bytes', models.BigIntegerField()),
                ('sha1', models.CharField(max_length=40)),
                ('sha256', models.CharField(max_length=64)),
                ('md5', models.CharField(max_length=32)),
                ('mimetype', models.CharField()),
                ('content_scope', models.CharField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField()),
                ('url', models.CharField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.releasefile')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
                ('target_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='fcapi.release')),
            ],
        ),
        migrations.CreateModel(
            name='Webcapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('source', models.CharField(db_index=True)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.TextField()),
                ('extra', models.JSONField()),
                ('original_url', models.TextField()),
                ('ts', models.DateTimeField()),
                ('content_scope', models.CharField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebcaptureCDX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surt', models.TextField()),
                ('ts', models.DateTimeField()),
                ('url', models.TextField()),
                ('mimetype', models.CharField()),
                ('status_code', models.SmallIntegerField()),
                ('sha1', models.CharField(max_length=40)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('webcapture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.webcapture')),
            ],
        ),
        migrations.CreateModel(
            name='WebcaptureURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField()),
                ('url', models.CharField()),
                ('webcapture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.webcapture')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseExtId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField()),
                ('id_value', models.CharField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
            options={
                'indexes': [models.Index(fields=['release_id', 'id_type'], name='fcapi_relea_release_ed8499_idx'), models.Index(fields=['id_type', 'id_value'], name='fcapi_relea_id_type_98e8bb_idx')],
            },
        ),
    ]
