# Generated by Django 5.1.5 on 2025-02-06 00:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='releaseextid',
            name='fcapi_relea_release_ed8499_idx',
        ),
        migrations.RemoveField(
            model_name='container',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='container',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='container',
            name='publication_status',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='wikidata_qid',
        ),
        migrations.RemoveField(
            model_name='fileset',
            name='content_scope',
        ),
        migrations.RemoveField(
            model_name='fileset',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='fileset',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='filesetfile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='filesetfile',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='release',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='release',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='release',
            name='withdrawn_date',
        ),
        migrations.RemoveField(
            model_name='release',
            name='withdrawn_year',
        ),
        migrations.RemoveField(
            model_name='releaseabstract',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='releasefile',
            name='content_scope',
        ),
        migrations.RemoveField(
            model_name='releasefile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='releasefile',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='webcapture',
            name='content_scope',
        ),
        migrations.RemoveField(
            model_name='webcapture',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='webcapture',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='webcapture',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='webcapturecdx',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='work',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='work',
            name='hidden',
        ),
        migrations.AddField(
            model_name='container',
            name='hidden_when',
            field=models.DateTimeField(help_text='when a given record was hidden', null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='hidden_when',
            field=models.DateTimeField(help_text='when a given record was hidden', null=True),
        ),
        migrations.AddField(
            model_name='fileset',
            name='hidden_when',
            field=models.DateTimeField(help_text='when a given record was hidden', null=True),
        ),
        migrations.AddField(
            model_name='filesetfile',
            name='hidden_when',
            field=models.DateTimeField(help_text='when a given record was hidden', null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='hidden_when',
            field=models.DateTimeField(help_text='when a given record was hidden', null=True),
        ),
        migrations.AddField(
            model_name='releaseabstract',
            name='language',
            field=models.CharField(blank=True, help_text='Primary language of abstract. Two-letter RFC1766/ISO639-1 language code.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='releaseabstract',
            name='license_slug',
            field=models.CharField(blank=True, help_text="short name for a license covering this release. for example, 'CC-BY-NA'.", null=True),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='hidden_when',
            field=models.DateTimeField(help_text='when a given record was hidden', null=True),
        ),
        migrations.AddField(
            model_name='webcapture',
            name='captured',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='date and time of capture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcapture',
            name='hidden_when',
            field=models.DateTimeField(help_text='when a given record was hidden', null=True),
        ),
        migrations.AddField(
            model_name='webcapturecdx',
            name='captured',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='capture time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='hidden_when',
            field=models.DateTimeField(help_text='when a given record was hidden', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.CharField(blank=True, choices=[('blog', 'blog'), ('book-series', 'book-series'), ('conference', 'conference'), ('conference-series', 'conference-series'), ('journal', 'journal'), ('magazine', 'magazine'), ('proceedings', 'proceedings'), ('repository', 'repository')], null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='extra',
            field=models.JSONField(help_text='arbitrary storage for additional key/value data found in upstream sources'),
        ),
        migrations.AlterField(
            model_name='container',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='issne',
            field=models.CharField(blank=True, help_text='an e-ISSN, or electronic ISSN. for digital versions of publications. This can be linked to a p-ISSN (issnp column) via an ISSN-L.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='issnl',
            field=models.CharField(blank=True, help_text='an ISSN-L, or linking ISSN. This is a grouping ISSN for publications that print in various media (eg, print and digital', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='issnp',
            field=models.CharField(blank=True, help_text='a p-ISSN, or print ISSN. for print versions of publications. This can be linked to an e-ISSN (issne column) via an ISSN-L.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='publisher',
            field=models.CharField(help_text="name of container's publisher"),
        ),
        migrations.AlterField(
            model_name='container',
            name='source',
            field=models.CharField(db_index=True, help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='container',
            name='wikidata_qid',
            field=models.CharField(blank=True, help_text='ID from the wikidata project. See https://www.wikidata.org/wiki/Wikidata:Identifiers', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='display_name',
            field=models.CharField(help_text='full name of a human to show in web front-ends'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='extra',
            field=models.JSONField(help_text='arbitrary storage for additional key/value data found in upstream sources'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='given_name',
            field=models.CharField(blank=True, help_text="'first' name of a human depending on context", null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='orcid',
            field=models.CharField(blank=True, help_text='external, unique identifier of a human author. See https://orcid.org/', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='source',
            field=models.CharField(db_index=True, help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='surname',
            field=models.CharField(blank=True, help_text="'last' name of a human depending on context", null=True),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='extra',
            field=models.JSONField(help_text='arbitrary storage for additional key/value data found in upstream sources'),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='source',
            field=models.CharField(db_index=True, help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='extra',
            field=models.JSONField(help_text='arbitrary storage for additional key/value data found in upstream sources'),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='md5',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='sha1',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='sha256',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='size_bytes',
            field=models.BigIntegerField(help_text='size in bytes of this file'),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='source',
            field=models.CharField(db_index=True, help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='fileurl',
            name='rel',
            field=models.CharField(choices=[('web', 'general public web site'), ('webarchive', 'a resource in a long-term web archive'), ('repository', 'a resource stored in an academic repository'), ('academicsocial', 'academic social network content'), ('publisher', "a resource on a publisher's homepage"), ('aggregator', 'full text aggregator or search engine like Semantic Scholar'), ('dweb', 'content on a distributed or decentralized web protocol like dat:// or ipfs://')], default='web'),
        ),
        migrations.AlterField(
            model_name='fileurl',
            name='url',
            field=models.URLField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='release',
            name='container',
            field=models.ForeignKey(help_text='the thing in which this release was published. for example, for a paper, its container is likely an academic journal', on_delete=django.db.models.deletion.CASCADE, to='fcapi.container'),
        ),
        migrations.AlterField(
            model_name='release',
            name='extra',
            field=models.JSONField(help_text='arbitrary storage for additional key/value data found in upstream sources'),
        ),
        migrations.AlterField(
            model_name='release',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='issue',
            field=models.CharField(blank=True, help_text='Issue of parent container in which this was published', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='language',
            field=models.CharField(blank=True, help_text='Primary language of release content. Two-letter RFC1766/ISO639-1 language code.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='license_slug',
            field=models.CharField(blank=True, help_text="short name for a license covering this release. for example, 'CC-BY-NA'", null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='number',
            field=models.CharField(blank=True, help_text='Arbitrary number in parent container in which this release was published. For example, technical reports use numbers instead of volumes.', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='original_title',
            field=models.CharField(blank=True, help_text='title in original language if title field value has been tranlasted', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='pages',
            field=models.CharField(blank=True, help_text='Free form text describing the page or page range that contains this release in its parent container', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='publisher',
            field=models.CharField(blank=True, help_text='Name of publisher, if known', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='refs',
            field=models.JSONField(blank=True, help_text='a JSON blob describing the citations of this release.', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(blank=True, help_text='exact date on which this release was published, if known', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_stage',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('draft', 'draft'), ('published', 'published'), ('retraction', 'retraction'), ('submitted', 'submitted'), ('updated', 'updated')], help_text='Location of release in publishing pipeline', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_type',
            field=models.CharField(blank=True, choices=[('article', 'article'), ('article-journal', 'article-journal'), ('article-magazine', 'article-magazine'), ('article-newspaper', 'article-newspaper'), ('book', 'book'), ('broadcast', 'broadcast'), ('chapter', 'chapter'), ('dataset', 'dataset'), ('entry', 'entry'), ('event', 'event'), ('figure', 'figure'), ('graphic', 'graphic'), ('hearing', 'hearing'), ('interview', 'interview'), ('legal_case', 'legal_case'), ('legislation', 'legislation'), ('manuscript', 'manuscript'), ('map', 'map'), ('motion_picture', 'motion_picture'), ('musical_score', 'musical_score'), ('pamphlet', 'pamphlet'), ('paper-conference', 'paper-conference'), ('patent', 'patent'), ('personal_communication', 'personal_communication'), ('post', 'post'), ('post-weblog', 'post-weblog'), ('regulation', 'regulation'), ('report', 'report'), ('review', 'review'), ('review-book', 'review-book'), ('software', 'software'), ('song', 'song'), ('speech', 'speech'), ('standard', 'standard'), ('thesis', 'thesis'), ('treaty', 'treaty'), ('webpage', 'webpage'), ('abstract', 'abstract'), ('editorial', 'editorial'), ('component', 'component'), ('peer_review', 'peer_review'), ('stub', 'stub'), ('retraction', 'retraction')], help_text='Kind of release. Mostly, we have article or article-journal. The choices were extracted from the original fatcat dataset', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_year',
            field=models.SmallIntegerField(help_text='Year in which this release was published. Separate from release_date since we often only know a year', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='source',
            field=models.CharField(db_index=True, help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='release',
            name='subtitle',
            field=models.CharField(blank=True, help_text='subtitle, if any, for a release', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(help_text='a title for the release'),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(blank=True, help_text='Arbitrary version string. Might be used by technical reports or software packages', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='volume',
            field=models.CharField(blank=True, help_text='Volume of parent container in which this was published', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='withdrawn_status',
            field=models.CharField(blank=True, help_text='free form field for stating why a release has been withdrawn. currently used values: concern, retracted, safety, spam, withdrawn.', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='work',
            field=models.ForeignKey(help_text='the work under which this release is grouped', on_delete=django.db.models.deletion.CASCADE, to='fcapi.work'),
        ),
        migrations.AlterField(
            model_name='releaseabstract',
            name='mimetype',
            field=models.CharField(default='text/plain'),
        ),
        migrations.AlterField(
            model_name='releaseabstract',
            name='sha1',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='extra',
            field=models.JSONField(help_text='JSON blob for additional metadata'),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='given_name',
            field=models.CharField(blank=True, help_text="'first' name of a human depending on context", null=True),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='index_val',
            field=models.SmallIntegerField(help_text='Position in list of contributors'),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='raw_affiliation',
            field=models.CharField(blank=True, help_text='Name of instituion or organization to which contributor belonged', null=True),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='raw_name',
            field=models.CharField(help_text="Name of the author as listed in the reference. If this reference is matched to an author in our database, this value might differ from the linked author's display name."),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='role',
            field=models.CharField(blank=True, choices=[('author', 'author'), ('editor', 'editor'), ('translator', 'translator')], help_text='role played by contributor', null=True),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='surname',
            field=models.CharField(blank=True, help_text="'last' name of a human depending on context", null=True),
        ),
        migrations.AlterField(
            model_name='releaseextid',
            name='id_type',
            field=models.CharField(choices=[('doi', 'doi'), ('pmid', 'pmid'), ('pmcid', 'pmcid'), ('wikidata_qid', 'wikidata_qid'), ('core_id', 'core_id'), ('ark', 'ark'), ('arxiv', 'arxiv'), ('dblp', 'dblp'), ('doaj', 'doaj'), ('hdl', 'hdl'), ('isbn13', 'isbn13'), ('jstor', 'jstor'), ('mag', 'mag')]),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='extra',
            field=models.JSONField(help_text='arbitrary storage for additional key/value data found in upstream sources'),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='md5',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='sha1',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='sha256',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='size_bytes',
            field=models.BigIntegerField(help_text='size in bytes of this file'),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='source',
            field=models.CharField(db_index=True, help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='releaseref',
            name='position',
            field=models.SmallIntegerField(help_text='Position in list of references'),
        ),
        migrations.AlterField(
            model_name='releaseref',
            name='release',
            field=models.ForeignKey(help_text='release in which this citation occurred', on_delete=django.db.models.deletion.CASCADE, to='fcapi.release'),
        ),
        migrations.AlterField(
            model_name='releaseref',
            name='target_release',
            field=models.ForeignKey(help_text='Release referenced by this citation', on_delete=django.db.models.deletion.CASCADE, related_name='target', to='fcapi.release'),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='extra',
            field=models.JSONField(help_text='arbitrary storage for additional key/value data found in upstream sources'),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='original_url',
            field=models.URLField(help_text='base URL of the resource.', max_length=100000),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='source',
            field=models.CharField(db_index=True, help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='webcapturecdx',
            name='status_code',
            field=models.SmallIntegerField(help_text='HTTP status code'),
        ),
        migrations.AlterField(
            model_name='webcapturecdx',
            name='surt',
            field=models.TextField(help_text='sortable URL format'),
        ),
        migrations.AlterField(
            model_name='webcapturecdx',
            name='url',
            field=models.URLField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='webcaptureurl',
            name='rel',
            field=models.CharField(choices=[('warc', 'warc'), ('wayback', 'wayback'), ('webarchive', 'webarchive')]),
        ),
        migrations.AlterField(
            model_name='webcaptureurl',
            name='url',
            field=models.URLField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='work',
            name='extra',
            field=models.JSONField(help_text='arbitrary storage for additional key/value data found in upstream sources'),
        ),
        migrations.AlterField(
            model_name='work',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='source',
            field=models.CharField(db_index=True, help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
    ]
