# Generated by Django 5.1.5 on 2025-03-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0002_releasefile_fcapi_releasefile_file_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='container',
            field=models.ForeignKey(blank=True, db_index=False, help_text='the thing in which this release was published. for example, for a paper, its container is likely an academic journal', null=True, on_delete=django.db.models.deletion.CASCADE, to='fcapi.container'),
        ),
    ]
