# Generated by Django 5.1.5 on 2025-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0002_remove_releaseextid_fcapi_relea_release_ed8499_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='legacy_ident',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-4444-fff000000001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creator',
            name='legacy_ident',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-4444-fff000000001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileset',
            name='legacy_rev',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-4444-fff000000001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='legacy_ident',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-4444-fff000000001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='legacy_rev',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-4444-fff000000001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releasefile',
            name='legacy_rev',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-4444-fff000000001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcapture',
            name='legacy_rev',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-4444-fff000000001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='legacy_ident',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-4444-fff000000001'),
            preserve_default=False,
        ),
    ]
