# Generated by Django 5.1.5 on 2025-03-13 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0003_alter_release_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseextid',
            name='release',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fcapi.release'),
        ),
        migrations.AddIndex(
            model_name='releaseextid',
            index=models.Index(fields=['release'], name='fcapi_releaseextid_release_idx'),
        ),
    ]
