# Generated by Django 5.1.5 on 2025-02-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0003_container_legacy_ident_creator_legacy_ident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='publisher',
            field=models.CharField(blank=True, help_text="name of container's publisher", null=True),
        ),
    ]
