# Generated by Django 5.1.5 on 2025-02-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0004_alter_container_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='extra',
            field=models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='extra',
            field=models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='extra',
            field=models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='extra',
            field=models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='extra',
            field=models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='extra',
            field=models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='extra',
            field=models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='extra',
            field=models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True),
        ),
    ]
