# Generated by Django 5.1.5 on 2025-02-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0005_alter_container_extra_alter_creator_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='issne',
            field=models.CharField(blank=True, db_index=True, help_text='an e-ISSN, or electronic ISSN. for digital versions of publications. This can be linked to a p-ISSN (issnp column) via an ISSN-L.', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='issnl',
            field=models.CharField(blank=True, db_index=True, help_text='an ISSN-L, or linking ISSN. This is a grouping ISSN for publications that print in various media (eg, print and digital', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='issnp',
            field=models.CharField(blank=True, db_index=True, help_text='a p-ISSN, or print ISSN. for print versions of publications. This can be linked to an e-ISSN (issne column) via an ISSN-L.', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='wikidata_qid',
            field=models.CharField(blank=True, db_index=True, help_text='ID from the wikidata project. See https://www.wikidata.org/wiki/Wikidata:Identifiers', null=True),
        ),
    ]
