# Generated by Django 5.1.5 on 2025-02-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0006_alter_container_issne_alter_container_issnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='legacy_container_ident',
            field=models.UUIDField(db_index=True, default='ed42317a-a9f5-4559-9de8-c2a41f832062'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='legacy_core_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='legacy_doi',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='legacy_pmcid',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='legacy_pmid',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='legacy_wikidata_qid',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='legacy_work_ident',
            field=models.UUIDField(db_index=True, default='ed42317a-a9f5-4559-9de8-c2a41f832062'),
            preserve_default=False,
        ),
    ]
