# Generated by Django 5.1.5 on 2025-02-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0007_release_legacy_container_ident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesetURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(choices=[('webarchive', 'web archive version of repository landing page'), ('repository', 'url of a live-web landing page or other location where content can be found'), ('platform', 'url of a live-web landing page or other location where content can be found'), ('web', 'url of a live-web landing page or other location where content can be found'), ('repository-bundle', "direct URL to a live-web 'archive' file like .zip"), ('webarchive-bundle', 'webarchive version of repository-bundle'), ('archive-bundle', 'file archive version of repository bundle'), ('repository-base', 'live-web base URL whence file paths can be appended to fetch individual files'), ('archive-base', 'base URL whence file paths can be appended to fetch individual files')], default='web')),
                ('url', models.URLField(max_length=100000)),
                ('fileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.fileset')),
            ],
        ),
    ]
