# Generated by Django 5.1.5 on 2025-03-14 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0007_rename_fcapi_releasecontrib_sha1_idx_fcapi_releasecontrib_creator_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseref',
            name='release',
            field=models.ForeignKey(db_index=False, help_text='release in which this citation occurred', on_delete=django.db.models.deletion.CASCADE, to='fcapi.release'),
        ),
        migrations.AlterField(
            model_name='releaseref',
            name='target_release',
            field=models.ForeignKey(db_index=False, help_text='Release referenced by this citation', on_delete=django.db.models.deletion.CASCADE, related_name='target', to='fcapi.release'),
        ),
    ]
