# Generated by Django 5.1.5 on 2025-03-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0008_alter_releaseref_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecontrib',
            name='creator',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fcapi.creator'),
        ),
    ]
