# Generated by Django 5.1.5 on 2025-02-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0008_fileseturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileseturl',
            name='legacy_fileset_rev',
            field=models.UUIDField(db_index=True, default='4d20bff6-f55e-11ef-803c-871947a953bb'),
            preserve_default=False,
        ),
    ]
