# Generated by Django 5.1.5 on 2025-03-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0009_fileseturl_legacy_fileset_rev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasecontrib',
            old_name='index_val',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='releaseabstract',
            name='license_slug',
        ),
        migrations.AddField(
            model_name='filesetfile',
            name='legacy_release_ident',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesetfile',
            name='path_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileurl',
            name='legacy_file_rev',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releaseabstract',
            name='legacy_release_rev',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releasecontrib',
            name='legacy_creator_ident',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releasecontrib',
            name='legacy_release_rev',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releaseextid',
            name='legacy_release_rev',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releasefile',
            name='legacy_release_ident',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releaseref',
            name='legacy_release_rev',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releaseref',
            name='legacy_target_release_ident',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcapturecdx',
            name='legacy_webcapture_rev',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcaptureurl',
            name='legacy_webcapture_rev',
            field=models.UUIDField(db_index=True, default='04fc7fd4-f636-11ef-bca2-ce2a48718fb2'),
            preserve_default=False,
        ),
    ]
