# Generated by Django 5.1.5 on 2025-03-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0009_alter_releasecontrib_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecontrib',
            name='extra',
            field=models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True),
        ),
    ]
