# Generated by Django 5.1.5 on 2025-03-04 00:15

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0010_rename_index_val_releasecontrib_position_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='releaseextid',
            new_name='extid_lookup_idx',
            old_name='fcapi_relea_id_type_98e8bb_idx',
        ),
        migrations.AlterField(
            model_name='container',
            name='issne',
            field=models.CharField(blank=True, help_text='an e-ISSN, or electronic ISSN. for digital versions of publications. This can be linked to a p-ISSN (issnp column) via an ISSN-L.', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='issnl',
            field=models.CharField(blank=True, help_text='an ISSN-L, or linking ISSN. This is a grouping ISSN for publications that print in various media (eg, print and digital', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='issnp',
            field=models.CharField(blank=True, help_text='a p-ISSN, or print ISSN. for print versions of publications. This can be linked to an e-ISSN (issne column) via an ISSN-L.', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='legacy_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='container',
            name='source',
            field=models.CharField(help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='container',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='container',
            name='wikidata_qid',
            field=models.CharField(blank=True, help_text='ID from the wikidata project. See https://www.wikidata.org/wiki/Wikidata:Identifiers', null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='legacy_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='creator',
            name='source',
            field=models.CharField(help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='legacy_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='source',
            field=models.CharField(help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='legacy_release_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='md5',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='sha1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='sha256',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='source',
            field=models.CharField(help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='fileseturl',
            name='legacy_fileset_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='fileurl',
            name='legacy_file_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='legacy_container_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='legacy_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='legacy_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='legacy_work_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='source',
            field=models.CharField(help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='release',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='releaseabstract',
            name='legacy_release_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='releaseabstract',
            name='sha1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='legacy_creator_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='legacy_release_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='releaseextid',
            name='legacy_release_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='legacy_release_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='legacy_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='md5',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='sha1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='sha256',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='source',
            field=models.CharField(help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='releaseref',
            name='legacy_release_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='releaseref',
            name='legacy_target_release_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='legacy_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='source',
            field=models.CharField(help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='webcapturecdx',
            name='legacy_webcapture_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='webcaptureurl',
            name='legacy_webcapture_rev',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='legacy_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='source',
            field=models.CharField(help_text='an arbitrary string denoting the data source whence a record was found'),
        ),
        migrations.AlterField(
            model_name='work',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['issnl'], name='fcapi_container_issnl_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['issne'], name='fcapi_container_issne_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['issnp'], name='fcapi_container_issnp_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['wikidata_qid'], name='fcapi_container_wikidata_qid_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['legacy_ident'], name='fcapi_container_legacy_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='creator',
            index=models.Index(fields=['legacy_ident'], name='fcapi_creator_legacy_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='fileset',
            index=models.Index(fields=['legacy_rev'], name='fcapi_fileset_legacy_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='filesetfile',
            index=models.Index(fields=['legacy_release_ident'], name='fcapi_filesetfile_legacy_release_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='fileseturl',
            index=models.Index(fields=['legacy_fileset_rev'], name='fcapi_fileseturl_legacy_fileset_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='fileurl',
            index=models.Index(fields=['legacy_file_rev'], name='fcapi_fileurl_legacy_file_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['legacy_ident'], name='fcapi_release_legacy_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['legacy_rev'], name='fcapi_release_legacy_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['legacy_work_ident'], name='fcapi_release_legacy_work_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['legacy_container_ident'], name='fcapi_release_legacy_container_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseabstract',
            index=models.Index(fields=['sha1'], name='fcapi_releaseabstract_sha1_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseabstract',
            index=models.Index(fields=['legacy_release_rev'], name='fcapi_releaseabstract_legacy_release_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='releasecontrib',
            index=models.Index(fields=['legacy_release_rev'], name='fcapi_releasecontrib_legacy_release_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='releasecontrib',
            index=models.Index(fields=['legacy_creator_ident'], name='fcapi_releasecontrib_legacy_creator_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseextid',
            index=models.Index(fields=['legacy_release_rev'], name='fcapi_releaseextid_legacy_release_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='releasefile',
            index=models.Index(fields=['legacy_rev'], name='fcapi_releasefile_legacy_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='releasefile',
            index=models.Index(fields=['legacy_release_ident'], name='fcapi_releasefile_legacy_release_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseref',
            index=models.Index(fields=['legacy_release_rev'], name='fcapi_releaseref_legacy_release_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseref',
            index=models.Index(fields=['legacy_target_release_ident'], name='fcapi_releaseref_legacy_target_release_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='webcapture',
            index=models.Index(fields=['legacy_rev'], name='fcapi_webcapture_legacy_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='webcapturecdx',
            index=models.Index(fields=['legacy_webcapture_rev'], name='fcapi_webcapturecdx_legacy_webcapture_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='webcaptureurl',
            index=models.Index(fields=['legacy_webcapture_rev'], name='fcapi_webcaptureurl_legacy_webcapture_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['legacy_ident'], name='fcapi_work_legacy_ident_idx'),
        ),
    ]
