# Generated by Django 5.1.5 on 2025-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0010_alter_releasecontrib_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecontrib',
            name='position',
            field=models.SmallIntegerField(blank=True, help_text='Position in list of contributors', null=True),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='raw_name',
            field=models.CharField(blank=True, help_text="Name of the author as listed in the reference. If this reference is matched to an author in our database, this value might differ from the linked author's display name.", null=True),
        ),
    ]
