# Generated by Django 5.1.5 on 2025-03-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0011_rename_fcapi_relea_id_type_98e8bb_idx_extid_lookup_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['updated'], name='fcapi_container_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['source'], name='fcapi_container_source_idx'),
        ),
    ]
