# Generated by Django 5.1.5 on 2025-03-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0012_container_fcapi_container_updated_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creator',
            index=models.Index(fields=['updated'], name='fcapi_creator_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='creator',
            index=models.Index(fields=['source'], name='fcapi_creator_source_idx'),
        ),
    ]
