# Generated by Django 5.1.5 on 2025-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0012_alter_file_md5_alter_file_sha1_alter_file_sha256_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='mimetype',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='mimetype',
            field=models.CharField(blank=True, null=True),
        ),
    ]
