# Generated by Django 5.1.5 on 2025-03-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0013_alter_file_mimetype_alter_filesetfile_mimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileset',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fcapi.release'),
        ),
    ]
