# Generated by Django 5.1.5 on 2025-03-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0013_creator_fcapi_creator_updated_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileset',
            index=models.Index(fields=['updated'], name='fcapi_fileset_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='fileset',
            index=models.Index(fields=['source'], name='fcapi_fileset_source_idx'),
        ),
        migrations.AddIndex(
            model_name='filesetfile',
            index=models.Index(fields=['updated'], name='fcapi_filesetfile_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='filesetfile',
            index=models.Index(fields=['source'], name='fcapi_filesetfile_source_idx'),
        ),
        migrations.AddIndex(
            model_name='filesetfile',
            index=models.Index(fields=['sha1'], name='fcapi_filesetfile_sha1_idx'),
        ),
        migrations.AddIndex(
            model_name='filesetfile',
            index=models.Index(fields=['sha256'], name='fcapi_filesetfile_sha256_idx'),
        ),
        migrations.AddIndex(
            model_name='filesetfile',
            index=models.Index(fields=['md5'], name='fcapi_filesetfile_md5_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['updated'], name='fcapi_release_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['source'], name='fcapi_release_source_idx'),
        ),
        migrations.AddIndex(
            model_name='releasefile',
            index=models.Index(fields=['updated'], name='fcapi_releasefile_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='releasefile',
            index=models.Index(fields=['source'], name='fcapi_releasefile_source_idx'),
        ),
        migrations.AddIndex(
            model_name='releasefile',
            index=models.Index(fields=['sha1'], name='fcapi_releasefile_sha1_idx'),
        ),
        migrations.AddIndex(
            model_name='releasefile',
            index=models.Index(fields=['sha256'], name='fcapi_releasefile_sha256_idx'),
        ),
        migrations.AddIndex(
            model_name='releasefile',
            index=models.Index(fields=['md5'], name='fcapi_releasefile_md5_idx'),
        ),
        migrations.AddIndex(
            model_name='webcapture',
            index=models.Index(fields=['updated'], name='fcapi_webcapture_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='webcapture',
            index=models.Index(fields=['source'], name='fcapi_webcapture_source_idx'),
        ),
    ]
