# Generated by Django 5.1.5 on 2025-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0014_fileset_fcapi_fileset_updated_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['updated'], name='fcapi_work_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['source'], name='fcapi_work_source_idx'),
        ),
    ]
