# Generated by Django 5.1.5 on 2025-03-06 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0015_work_fcapi_work_updated_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='container',
            field=models.ForeignKey(db_index=False, help_text='the thing in which this release was published. for example, for a paper, its container is likely an academic journal', on_delete=django.db.models.deletion.CASCADE, to='fcapi.container'),
        ),
        migrations.AlterField(
            model_name='release',
            name='work',
            field=models.ForeignKey(db_index=False, help_text='the work under which this release is grouped', on_delete=django.db.models.deletion.CASCADE, to='fcapi.work'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['work_id'], name='fcapi_release_work_id_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['container_id'], name='fcapi_release_container_id_idx'),
        ),
    ]
