# Generated by Django 5.1.5 on 2025-05-28 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0019_alter_releasefile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseabstract',
            name='language',
            field=models.TextField(blank=True, help_text='Primary language of abstract. Two-letter RFC1766/ISO639-1 language code.', null=True),
        ),
        migrations.AlterField(
            model_name='releaseabstract',
            name='release',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to='fcapi.release'),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='release',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='contribs', to='fcapi.release'),
        ),
        migrations.AlterField(
            model_name='releaseextid',
            name='release',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='extids', to='fcapi.release'),
        ),
        migrations.AlterField(
            model_name='releaseref',
            name='release',
            field=models.ForeignKey(db_index=False, help_text='release in which this citation occurred', on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='fcapi.release'),
        ),
        migrations.AlterField(
            model_name='webcapturecdx',
            name='webcapture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdx_lines', to='fcapi.webcapture'),
        ),
        migrations.AlterField(
            model_name='webcaptureurl',
            name='webcapture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='fcapi.webcapture'),
        ),
    ]
