# Generated by Django 5.1.5 on 2025-05-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0020_alter_releaseabstract_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseabstract',
            name='mimetype',
            field=models.CharField(default='text/plain', null=True),
        ),
    ]
