# Generated by Django 5.1.5 on 2025-03-11 15:13

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('source', models.CharField(help_text='an arbitrary string denoting the data source whence a record was found')),
                ('hidden_reason', models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True)),
                ('hidden_when', models.DateTimeField(help_text='when a given record was hidden', null=True)),
                ('extra', models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True)),
                ('legacy_rev', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('size_bytes', models.BigIntegerField(help_text='size in bytes of this file')),
                ('sha1', models.CharField(max_length=40)),
                ('sha256', models.CharField(max_length=64)),
                ('md5', models.CharField(max_length=32)),
                ('mimetype', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fileset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('source', models.CharField(help_text='an arbitrary string denoting the data source whence a record was found')),
                ('hidden_reason', models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True)),
                ('hidden_when', models.DateTimeField(help_text='when a given record was hidden', null=True)),
                ('extra', models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True)),
                ('legacy_rev', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('source', models.CharField(help_text='an arbitrary string denoting the data source whence a record was found')),
                ('hidden_reason', models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True)),
                ('hidden_when', models.DateTimeField(help_text='when a given record was hidden', null=True)),
                ('extra', models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True)),
                ('legacy_rev', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField()),
                ('container_type', models.CharField(blank=True, choices=[('blog', 'blog'), ('book-series', 'book-series'), ('conference', 'conference'), ('conference-series', 'conference-series'), ('journal', 'journal'), ('magazine', 'magazine'), ('proceedings', 'proceedings'), ('repository', 'repository')], null=True)),
                ('publisher', models.CharField(blank=True, help_text="name of container's publisher", null=True)),
                ('issnl', models.CharField(blank=True, help_text='an ISSN-L, or linking ISSN. This is a grouping ISSN for publications that print in various media (eg, print and digital', null=True)),
                ('issne', models.CharField(blank=True, help_text='an e-ISSN, or electronic ISSN. for digital versions of publications. This can be linked to a p-ISSN (issnp column) via an ISSN-L.', null=True)),
                ('issnp', models.CharField(blank=True, help_text='a p-ISSN, or print ISSN. for print versions of publications. This can be linked to an e-ISSN (issne column) via an ISSN-L.', null=True)),
                ('wikidata_qid', models.CharField(blank=True, help_text='ID from the wikidata project. See https://www.wikidata.org/wiki/Wikidata:Identifiers', null=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['updated'], name='fcapi_container_updated_idx'), models.Index(fields=['source'], name='fcapi_container_source_idx'), models.Index(fields=['legacy_rev'], name='fcapi_container_legacy_rev_idx'), models.Index(fields=['issnl'], name='fcapi_container_issnl_idx'), models.Index(fields=['issne'], name='fcapi_container_issne_idx'), models.Index(fields=['issnp'], name='fcapi_container_issnp_idx'), models.Index(fields=['wikidata_qid'], name='fcapi_container_wikidata_qid_idx')],
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('source', models.CharField(help_text='an arbitrary string denoting the data source whence a record was found')),
                ('hidden_reason', models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True)),
                ('hidden_when', models.DateTimeField(help_text='when a given record was hidden', null=True)),
                ('extra', models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True)),
                ('legacy_rev', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('display_name', models.CharField(help_text='full name of a human to show in web front-ends')),
                ('given_name', models.CharField(blank=True, help_text="'first' name of a human depending on context", null=True)),
                ('surname', models.CharField(blank=True, help_text="'last' name of a human depending on context", null=True)),
                ('orcid', models.CharField(blank=True, help_text='external, unique identifier of a human author. See https://orcid.org/', null=True, unique=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['updated'], name='fcapi_creator_updated_idx'), models.Index(fields=['source'], name='fcapi_creator_source_idx'), models.Index(fields=['legacy_rev'], name='fcapi_creator_legacy_rev_idx')],
            },
        ),
        migrations.CreateModel(
            name='FilesetURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(choices=[('webarchive', 'web archive version of repository landing page'), ('repository', 'url of a live-web landing page or other location where content can be found'), ('platform', 'url of a live-web landing page or other location where content can be found'), ('web', 'url of a live-web landing page or other location where content can be found'), ('repository-bundle', "direct URL to a live-web 'archive' file like .zip"), ('webarchive-bundle', 'webarchive version of repository-bundle'), ('archive-bundle', 'file archive version of repository bundle'), ('repository-base', 'live-web base URL whence file paths can be appended to fetch individual files'), ('archive-base', 'base URL whence file paths can be appended to fetch individual files')], default='web')),
                ('url', models.URLField(max_length=100000)),
                ('fileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.fileset')),
            ],
        ),
        migrations.CreateModel(
            name='FileURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(choices=[('web', 'general public web site'), ('webarchive', 'a resource in a long-term web archive'), ('repository', 'a resource stored in an academic repository'), ('academicsocial', 'academic social network content'), ('publisher', "a resource on a publisher's homepage"), ('aggregator', 'full text aggregator or search engine like Semantic Scholar'), ('dweb', 'content on a distributed or decentralized web protocol like dat:// or ipfs://')], default='web')),
                ('url', models.URLField(max_length=100000)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.file')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('source', models.CharField(help_text='an arbitrary string denoting the data source whence a record was found')),
                ('hidden_reason', models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True)),
                ('hidden_when', models.DateTimeField(help_text='when a given record was hidden', null=True)),
                ('extra', models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True)),
                ('legacy_rev', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(help_text='a title for the release')),
                ('original_title', models.CharField(blank=True, help_text='title in original language if title field value has been tranlasted', null=True)),
                ('subtitle', models.CharField(blank=True, help_text='subtitle, if any, for a release', null=True)),
                ('release_type', models.CharField(blank=True, choices=[('article', 'article'), ('article-journal', 'article-journal'), ('article-magazine', 'article-magazine'), ('article-newspaper', 'article-newspaper'), ('book', 'book'), ('broadcast', 'broadcast'), ('chapter', 'chapter'), ('dataset', 'dataset'), ('entry', 'entry'), ('event', 'event'), ('figure', 'figure'), ('graphic', 'graphic'), ('hearing', 'hearing'), ('interview', 'interview'), ('legal_case', 'legal_case'), ('legislation', 'legislation'), ('manuscript', 'manuscript'), ('map', 'map'), ('motion_picture', 'motion_picture'), ('musical_score', 'musical_score'), ('pamphlet', 'pamphlet'), ('paper-conference', 'paper-conference'), ('patent', 'patent'), ('personal_communication', 'personal_communication'), ('post', 'post'), ('post-weblog', 'post-weblog'), ('regulation', 'regulation'), ('report', 'report'), ('review', 'review'), ('review-book', 'review-book'), ('software', 'software'), ('song', 'song'), ('speech', 'speech'), ('standard', 'standard'), ('thesis', 'thesis'), ('treaty', 'treaty'), ('webpage', 'webpage'), ('abstract', 'abstract'), ('editorial', 'editorial'), ('component', 'component'), ('peer_review', 'peer_review'), ('stub', 'stub'), ('retraction', 'retraction')], help_text='Kind of release. Mostly, we have article or article-journal. The choices were extracted from the original fatcat dataset', null=True)),
                ('release_stage', models.CharField(blank=True, choices=[('accepted', 'accepted'), ('draft', 'draft'), ('published', 'published'), ('retraction', 'retraction'), ('submitted', 'submitted'), ('updated', 'updated')], help_text='Location of release in publishing pipeline', null=True)),
                ('release_date', models.DateField(blank=True, help_text='exact date on which this release was published, if known', null=True)),
                ('release_year', models.SmallIntegerField(help_text='Year in which this release was published. Separate from release_date since we often only know a year', null=True)),
                ('volume', models.CharField(blank=True, help_text='Volume of parent container in which this was published', null=True)),
                ('issue', models.CharField(blank=True, help_text='Issue of parent container in which this was published', null=True)),
                ('pages', models.CharField(blank=True, help_text='Free form text describing the page or page range that contains this release in its parent container', null=True)),
                ('number', models.CharField(blank=True, help_text='Arbitrary number in parent container in which this release was published. For example, technical reports use numbers instead of volumes.', null=True)),
                ('version', models.CharField(blank=True, help_text='Arbitrary version string. Might be used by technical reports or software packages', null=True)),
                ('publisher', models.CharField(blank=True, help_text='Name of publisher, if known', null=True)),
                ('language', models.CharField(blank=True, help_text='Primary language of release content. Two-letter RFC1766/ISO639-1 language code.', max_length=2, null=True)),
                ('license_slug', models.CharField(blank=True, help_text="short name for a license covering this release. for example, 'CC-BY-NA'", null=True)),
                ('withdrawn_status', models.CharField(blank=True, help_text='free form field for stating why a release has been withdrawn. currently used values: concern, retracted, safety, spam, withdrawn.', null=True)),
                ('refs', models.JSONField(blank=True, help_text='a JSON blob describing the citations of this release.', null=True)),
                ('legacy_doi', models.CharField(blank=True, null=True)),
                ('legacy_pmid', models.CharField(blank=True, null=True)),
                ('legacy_pmcid', models.CharField(blank=True, null=True)),
                ('legacy_wikidata_qid', models.CharField(blank=True, null=True)),
                ('legacy_core_id', models.CharField(blank=True, null=True)),
                ('container', models.ForeignKey(db_index=False, help_text='the thing in which this release was published. for example, for a paper, its container is likely an academic journal', on_delete=django.db.models.deletion.CASCADE, to='fcapi.container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fileset',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release'),
        ),
        migrations.CreateModel(
            name='ReleaseAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimetype', models.CharField(default='text/plain')),
                ('language', models.CharField(blank=True, help_text='Primary language of abstract. Two-letter RFC1766/ISO639-1 language code.', max_length=2, null=True)),
                ('sha1', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseContrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(help_text="Name of the author as listed in the reference. If this reference is matched to an author in our database, this value might differ from the linked author's display name.")),
                ('given_name', models.CharField(blank=True, help_text="'first' name of a human depending on context", null=True)),
                ('surname', models.CharField(blank=True, help_text="'last' name of a human depending on context", null=True)),
                ('role', models.CharField(blank=True, choices=[('author', 'author'), ('editor', 'editor'), ('translator', 'translator')], help_text='role played by contributor', null=True)),
                ('raw_affiliation', models.CharField(blank=True, help_text='Name of instituion or organization to which contributor belonged', null=True)),
                ('position', models.SmallIntegerField(help_text='Position in list of contributors')),
                ('extra', models.JSONField(help_text='JSON blob for additional metadata')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.creator')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseExtId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('doi', 'doi'), ('pmid', 'pmid'), ('pmcid', 'pmcid'), ('wikidata_qid', 'wikidata_qid'), ('core_id', 'core_id'), ('ark', 'ark'), ('arxiv', 'arxiv'), ('dblp', 'dblp'), ('doaj', 'doaj'), ('hdl', 'hdl'), ('isbn13', 'isbn13'), ('jstor', 'jstor'), ('mag', 'mag')])),
                ('id_value', models.CharField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.file')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='releases',
            field=models.ManyToManyField(through='fcapi.ReleaseFile', to='fcapi.release'),
        ),
        migrations.CreateModel(
            name='ReleaseRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(help_text='Position in list of references')),
                ('release', models.ForeignKey(help_text='release in which this citation occurred', on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
                ('target_release', models.ForeignKey(help_text='Release referenced by this citation', on_delete=django.db.models.deletion.CASCADE, related_name='target', to='fcapi.release')),
            ],
        ),
        migrations.CreateModel(
            name='Webcapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('source', models.CharField(help_text='an arbitrary string denoting the data source whence a record was found')),
                ('hidden_reason', models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True)),
                ('hidden_when', models.DateTimeField(help_text='when a given record was hidden', null=True)),
                ('extra', models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True)),
                ('legacy_rev', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('original_url', models.URLField(help_text='base URL of the resource.', max_length=100000)),
                ('captured', models.DateTimeField(help_text='date and time of capture')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebcaptureCDX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surt', models.TextField(help_text='sortable URL format')),
                ('captured', models.DateTimeField(help_text='capture time')),
                ('url', models.URLField(max_length=100000)),
                ('mimetype', models.CharField()),
                ('status_code', models.SmallIntegerField(help_text='HTTP status code')),
                ('sha1', models.CharField(max_length=40)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('webcapture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.webcapture')),
            ],
        ),
        migrations.CreateModel(
            name='WebcaptureURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(choices=[('warc', 'warc'), ('wayback', 'wayback'), ('webarchive', 'webarchive')])),
                ('url', models.URLField(max_length=100000)),
                ('webcapture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.webcapture')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('source', models.CharField(help_text='an arbitrary string denoting the data source whence a record was found')),
                ('hidden_reason', models.TextField(blank=True, help_text='explanatory information why an entity was hidden', null=True)),
                ('hidden_when', models.DateTimeField(help_text='when a given record was hidden', null=True)),
                ('extra', models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True)),
                ('legacy_rev', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['updated'], name='fcapi_work_updated_idx'), models.Index(fields=['source'], name='fcapi_work_source_idx'), models.Index(fields=['legacy_rev'], name='fcapi_work_legacy_rev_idx')],
            },
        ),
        migrations.AddField(
            model_name='release',
            name='work',
            field=models.ForeignKey(db_index=False, help_text='the work under which this release is grouped', on_delete=django.db.models.deletion.CASCADE, to='fcapi.work'),
        ),
        migrations.CreateModel(
            name='FilesetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_bytes', models.BigIntegerField(help_text='size in bytes of this file')),
                ('sha1', models.CharField(max_length=40)),
                ('sha256', models.CharField(max_length=64)),
                ('md5', models.CharField(max_length=32)),
                ('mimetype', models.CharField()),
                ('path_name', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, help_text='arbitrary storage for additional key/value data found in upstream sources', null=True)),
                ('fileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapi.fileset')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['sha1'], name='fcapi_filesetfile_sha1_idx'), models.Index(fields=['sha256'], name='fcapi_filesetfile_sha256_idx'), models.Index(fields=['md5'], name='fcapi_filesetfile_md5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fileset',
            index=models.Index(fields=['updated'], name='fcapi_fileset_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='fileset',
            index=models.Index(fields=['source'], name='fcapi_fileset_source_idx'),
        ),
        migrations.AddIndex(
            model_name='fileset',
            index=models.Index(fields=['legacy_rev'], name='fcapi_fileset_legacy_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseabstract',
            index=models.Index(fields=['sha1'], name='fcapi_releaseabstract_sha1_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseextid',
            index=models.Index(fields=['id_type', 'id_value'], name='extid_lookup_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='releasefile',
            unique_together={('file', 'release')},
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['updated'], name='fcapi_file_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['source'], name='fcapi_file_source_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['legacy_rev'], name='fcapi_file_legacy_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['sha1'], name='fcapi_file_sha1_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['sha256'], name='fcapi_file_sha256_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['md5'], name='fcapi_file_md5_idx'),
        ),
        migrations.AddIndex(
            model_name='webcapture',
            index=models.Index(fields=['updated'], name='fcapi_webcapture_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='webcapture',
            index=models.Index(fields=['source'], name='fcapi_webcapture_source_idx'),
        ),
        migrations.AddIndex(
            model_name='webcapture',
            index=models.Index(fields=['legacy_rev'], name='fcapi_webcapture_legacy_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['updated'], name='fcapi_release_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['source'], name='fcapi_release_source_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['legacy_rev'], name='fcapi_release_legacy_rev_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['work_id'], name='fcapi_release_work_id_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['container_id'], name='fcapi_release_container_id_idx'),
        ),
    ]
