# Generated by Django 5.1.5 on 2025-03-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='releasefile',
            index=models.Index(fields=['file'], name='fcapi_releasefile_file_idx'),
        ),
        migrations.AddIndex(
            model_name='releasefile',
            index=models.Index(fields=['release'], name='fcapi_releasefile_release_idx'),
        ),
    ]
