# Generated by Django 5.1.5 on 2025-03-14 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0004_alter_releaseextid_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseabstract',
            name='release',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fcapi.release'),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='creator',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fcapi.creator'),
        ),
        migrations.AlterField(
            model_name='releasecontrib',
            name='release',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fcapi.release'),
        ),
        migrations.AddIndex(
            model_name='releaseabstract',
            index=models.Index(fields=['release'], name='fcapi_releaseabstract_release_idx'),
        ),
        migrations.AddIndex(
            model_name='releasecontrib',
            index=models.Index(fields=['release'], name='fcapi_releasecontrib_release_idx'),
        ),
        migrations.AddIndex(
            model_name='releasecontrib',
            index=models.Index(fields=['creator'], name='fcapi_releasecontrib_sha1_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseref',
            index=models.Index(fields=['release'], name='fcapi_releaseref_release_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseref',
            index=models.Index(fields=['target_release'], name='fcapi_releaseref_sha1_idx'),
        ),
    ]
