# Generated by Django 5.1.5 on 2025-03-14 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0005_alter_releaseabstract_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileurl',
            name='file',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fcapi.file'),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='file',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fcapi.file'),
        ),
        migrations.AddIndex(
            model_name='fileurl',
            index=models.Index(fields=['file'], name='fcapi_fileurl_file_idx'),
        ),
    ]
