# Generated by Django 5.1.5 on 2025-03-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0006_alter_fileurl_file_alter_releasefile_file_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='releasecontrib',
            new_name='fcapi_releasecontrib_creator_idx',
            old_name='fcapi_releasecontrib_sha1_idx',
        ),
        migrations.RenameIndex(
            model_name='releaseref',
            new_name='fcapi_releaseref_target_release_idx',
            old_name='fcapi_releaseref_sha1_idx',
        ),
    ]
