# Generated by Django 5.1.5 on 2025-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0011_alter_releasecontrib_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='md5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, help_text='size in bytes of this file', null=True),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='md5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='sha1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='filesetfile',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, help_text='size in bytes of this file', null=True),
        ),
    ]
