# Generated by Django 5.1.5 on 2025-03-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0014_alter_fileset_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcapturecdx',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
