# Generated by Django 5.1.5 on 2025-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0015_alter_webcapturecdx_size_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcapturecdx',
            name='status_code',
            field=models.SmallIntegerField(blank=True, help_text='HTTP status code', null=True),
        ),
    ]
