# Generated by Django 5.1.5 on 2025-03-27 15:59

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0016_alter_webcapturecdx_status_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                #('expiry', models.DateTimeField(blank=True, default=djscholar.fcapi.models.get_default_token_expiry, null=True)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=100)),
            ],
        ),
    ]
