# Generated by Django 5.1.5 on 2025-03-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0017_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
