# Generated by Django 5.1.5 on 2025-04-11 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0018_delete_authtoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='releasefile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='release',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='fcapi.release'),
        ),
        migrations.AddConstraint(
            model_name='releasefile',
            constraint=models.UniqueConstraint(fields=('file', 'release'), name='fcapi_releasefile_file_release_uniq'),
        ),
    ]
