# Generated by Django 5.1.5 on 2025-09-24 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0021_alter_releaseabstract_mimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileurl',
            name='file',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='fcapi.file'),
        ),
    ]
