# Generated by Django 5.1.5 on 2025-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0022_alter_fileurl_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='legacy_rev',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='legacy_rev',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='legacy_rev',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='legacy_rev',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='legacy_rev',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='legacy_rev',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='legacy_rev',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
