# Generated by Django 5.1.5 on 2025-09-26 20:05

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0023_alter_container_legacy_rev_alter_creator_legacy_rev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='creator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='release',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='webcapture',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
