# Generated by Django 5.1.5 on 2026-04-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('fcapi', '0024_alter_container_created_alter_creator_created_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "fcapi_container_created_idx" ON "fcapi_container" ("created")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "fcapi_container_created_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='container',
                    index=models.Index(fields=['created'], name='fcapi_container_created_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "fcapi_creator_created_idx" ON "fcapi_creator" ("created")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "fcapi_creator_created_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='creator',
                    index=models.Index(fields=['created'], name='fcapi_creator_created_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "fcapi_file_created_idx" ON "fcapi_file" ("created")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "fcapi_file_created_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='file',
                    index=models.Index(fields=['created'], name='fcapi_file_created_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "fcapi_fileset_created_idx" ON "fcapi_fileset" ("created")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "fcapi_fileset_created_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='fileset',
                    index=models.Index(fields=['created'], name='fcapi_fileset_created_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "fcapi_release_created_idx" ON "fcapi_release" ("created")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "fcapi_release_created_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='release',
                    index=models.Index(fields=['created'], name='fcapi_release_created_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "fcapi_webcapture_created_idx" ON "fcapi_webcapture" ("created")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "fcapi_webcapture_created_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='webcapture',
                    index=models.Index(fields=['created'], name='fcapi_webcapture_created_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "fcapi_work_created_idx" ON "fcapi_work" ("created")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "fcapi_work_created_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='work',
                    index=models.Index(fields=['created'], name='fcapi_work_created_idx'),
                ),
            ],
        ),
    ]
