# Generated by Django 5.1.5 on 2026-04-02 22:14

import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('fcapi', '0024_alter_container_created_alter_creator_created_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['created'], name='fcapi_container_created_idx'),
        ),
        migrations.AddIndex(
            model_name='creator',
            index=models.Index(fields=['created'], name='fcapi_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created'], name='fcapi_file_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fileset',
            index=models.Index(fields=['created'], name='fcapi_fileset_created_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['created'], name='fcapi_release_created_idx'),
        ),
        migrations.AddIndex(
            model_name='webcapture',
            index=models.Index(fields=['created'], name='fcapi_webcapture_created_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['created'], name='fcapi_work_created_idx'),
        ),
    ]
