import random
import re
import string
from datetime import datetime, timedelta

from faker.providers import BaseProvider


class ExtIDProvider(BaseProvider):
    """
    This class provides generators for various academic identifiers. These
    methods were initially generated by Claude and then
    golfed/tweaked/corrected.
    """
    def issn(self) -> str:
        """
        Generate a random ISSN (International Standard Serial Number).

        An ISSN is an 8-digit code used to identify periodical publications.
        Format: XXXX-XXXX where the last digit is a check digit (0-9 or X).

        See also: https://www.loc.gov/issn/basics/basics-checkdigit.html
        """
        digits = [random.randint(0, 9) for _ in range(7)]

        # Calculate the check digit
        # Each digit is multiplied by its position (8 to 2)
        # Sum the products and calculate the remainder when divided by 11
        weights = range(8, 1, -1)
        checksum = sum(d * w for d, w in zip(digits, weights)) % 11

        # The check digit is 11 minus the remainder (or 0 if remainder is 0)
        # If the result is 10, it's represented as "X"
        check_digit = 11 - checksum
        if check_digit == 11:
            check_digit = 0
        elif check_digit == 10:
            check_digit = "X"

        # Format the ISSN as XXXX-XXXX
        issn_first_part = "".join(str(d) for d in digits[:4])
        issn_second_part = "".join(str(d) for d in digits[4:]) + str(check_digit)

        return f"{issn_first_part}-{issn_second_part}"

    def wikidata_qid(self) -> str:
        """
        Generate a random Wikidata QID; eg: Q42, Q1, Q12345678
        """
        return "Q" + self.numerify("#"*9)

    def doi(self) -> str:
        """
        Generate a random DOI (Digital Object Identifier): 10.XXXX/YYYYYYYY
        """
        prefix_digits = self.random_int(1,4)
        suffix_length = self.random_int(1,100)
        # Generate prefix - always starts with 10.
        prefix = "10." + self.numerify("#"*prefix_digits)

        # Generate suffix - can contain uppercase letters, lowercase letters,
        # digits, and some special characters
        valid_chars = string.ascii_letters + string.digits + "-_.;()/+"
        suffix = "".join(self.random_element(valid_chars) for _ in range(suffix_length))

        # Ensure the suffix starts with a letter or a number
        while not re.match(r"^[a-zA-Z0-9]", suffix):
            suffix = self.random_element(string.ascii_letters + string.digits) + suffix[1:]

        return f"{prefix}/{suffix}"

    def pmcid(self) -> str:
        """
        Generate a random PMCID (PubMed Central ID), eg: PMC1234567
        """
        digit_length = self.random_int(3,8)
        # Generate a random number with the specified number of digits
        # Make sure the first digit isn't 0 to maintain consistent length
        first_digit = self.random_int(1, 9)
        rest_digits = "".join(self.random_digit() for _ in range(digit_length - 1))

        return f"PMC{first_digit}{rest_digits}"

    def pmid(self) -> str:
        """
        Generate a random PMID (PubMed ID); a length 8 random sequence of
        numbers.
        """
        length = 8

        # Generate a random number with the specified number of digits
        # Make sure the first digit isn"t 0 to maintain consistent length
        first_digit = self.random_int(1, 9)
        rest_digits = "".join(self.random_element("0123456789") for _ in range(length - 1))

        return f"{first_digit}{rest_digits}"

    def core_id(self) -> str:
        """
        Generate a random CORE ID; a length 8 random sequence of numbers.
        """
        length = 8

        # Generate a random number with the specified number of digits
        # Make sure the first digit isn't 0 to maintain consistent length
        first_digit = self.random_int(1, 9)
        rest_digits = "".join(self.random_element("0123456789") for _ in range(length - 1))

        return f"{first_digit}{rest_digits}"

    def ark(self) -> str:
        """
        Generate a random ARK (Archival Resource Key) identifier,
        eg: ark:/NAAN/Name[Qualifier]
        """
        # NAAN (Name Assigning Authority Number) - 5 digits
        naan = self.numerify("#"*5)

        # Name - alphanumeric with some special characters
        valid_name_chars = string.ascii_letters + string.digits + "=~*+@_.$"
        name_length = self.random_int(6, 12)
        name = "".join(self.random_element(valid_name_chars) for _ in range(name_length))

        # Qualifier (optional) - alphanumeric with some special characters
        include_qualifier = self.random_element([True, False])
        qualifier = ""
        if include_qualifier:
            qualifier_length = self.random_int(3, 8)
            qualifier = "/" + "".join(self.random_element(valid_name_chars)
                                      for _ in range(qualifier_length))

        return f"ark:/{naan}/{name}{qualifier}"


    def arxiv(self) -> str:
        """
        Generate a random arXiv identifier in either new or old format.

        New format: YYMM.NNNNN or YYMM.NNNNNvV
        Old format: arch-ive/YYMMNNN or arch-ive/YYMMNNN
        """
        use_new_format = self.random_element([True, False])
        if use_new_format:
            # New format: YYMM.NNNNN or YYMM.NNNNNvV
            # YY = year, MM = month, NNNNN = 5-digit number, V = version (optional)

            # Generate a random date from 2007 onwards
            start_date = datetime(2007, 4, 1)  # New format started in April 2007
            end_date = datetime.now()
            random_date = start_date + timedelta(
                days=self.random_int(0, (end_date - start_date).days)
            )

            # Format the date part
            date_part = random_date.strftime("%y%m")

            # Generate the 5-digit number (can start with 0)
            number_part = self.numerify("#"*5)

            # Decide if we include a version number
            include_version = self.random_element([True, False])
            version_part = ""
            if include_version:
                version_part = f"v{self.random_int(1, 5)}"

            return f"{date_part}.{number_part}{version_part}"

        # Old format: arch-ive/YYMMNNN or arch-ive/YYMMNNN
        # arch-ive = subject area, YY = year, MM = month, NNN = 3-digit number

        # Common subject areas
        subject_areas = [
            "astro-ph", "cond-mat", "cs", "gr-qc", "hep-ex", "hep-lat",
            "hep-ph", "hep-th", "math", "math-ph", "nlin", "nucl-ex",
            "nucl-th", "physics", "quant-ph", "q-bio"
        ]

        # Generate a random date from 1991 to 2007
        start_date = datetime(1991, 8, 1)  # arXiv started in August 1991
        end_date = datetime(2007, 3, 31)  # Last day of old format
        random_date = start_date + timedelta(
            days=self.random_int(0, (end_date - start_date).days)
        )

        date_part = random_date.strftime("%y%m")
        number_part = self.numerify("#"*3)

        subject_area = self.random_element(subject_areas)

        return f"{subject_area}/{date_part}{number_part}"

    def dblp_id(self) -> str:
        """
        Generate a random DBLP identifier.

        DBLP IDs generally follow patterns like:
        - conf/name/AuthorYY (for conference papers)
        - journals/name/AuthorYY (for journal articles)
        - books/name/AuthorYY (for books)
        - series/name/AuthorYYa (for series volumes)
        """
        # Potential publication types
        pub_types = ["conf", "journals", "books", "series", "reference", "phd"]
        pub_type = self.random_element(pub_types)

        # Some common venue/journal abbreviations
        venues = [
            "tods", "tois", "tkde", "vldb", "sigmod", "kdd", "www", "icde",
            "tocs", "toplas", "tods", "tog", "siggraph", "cikm", "icml",
            "nips", "aaai", "ijcai", "iclr", "acl", "cvpr", "iccv", "eccv",
            "sigir", "cscw", "chi", "uist", "pldi", "popl", "oopsla"
        ]
        venue = self.random_element(venues)

        # Generate author name (last name)
        last_name_length = self.random_int(4, 10)
        author = "".join(self.random_element(string.ascii_lowercase) for _ in range(last_name_length))
        author = author.capitalize()

        # Generate year (typically 2 digits)
        # Use years between 80 (1980) and current year's last 2 digits
        current_year = datetime.now().year % 100
        year = str(self.random_int(80, current_year)).zfill(2)

        # Sometimes an additional letter is added for disambiguation
        add_letter = self.random_element([True, False])
        letter_suffix = self.random_element(string.ascii_lowercase) if add_letter else ""

        return f"{pub_type}/{venue}/{author}{year}{letter_suffix}"

    def doaj_id(self) -> str:
        """
        Generate a random DOAJ (Directory of Open Access Journals) identifier.
        """
        # DOAJ article IDs are typically long alphanumeric strings
        # They're often UUIDs without hyphens
        return self.hexify("^"*32)

    def hdl(self) -> str:
        """
        Generate a random HDL (Handle) identifier.
        """
        # Prefix - typically a number assigned to an organization
        prefix = self.numerify("#"*5)

        # Generate suffix - can be almost any string, but commonly contains
        # alphanumeric characters and some special characters
        suffix_length = self.random_int(6, 15)
        valid_chars = string.ascii_letters + string.digits + "-._~:+="
        suffix = "".join(self.random_element(valid_chars) for _ in range(suffix_length))

        return f"{prefix}/{suffix}"

    def isbn13(self) -> str:
        """
        Generate a random ISBN-13 identifier with valid check digit.
        """
        # ISBN-13 starts with either 978 or 979 (GS1 prefix for books)
        prefix = self.random_element(["978", "979"])

        # Generate 9 random digits (after prefix, before check digit)
        digits = [self.random_int(0, 9) for _ in range(9)]

        # Convert prefix to list of integers
        prefix_digits = [int(digit) for digit in prefix]

        # Combine prefix and 9 random digits
        isbn_digits = prefix_digits + digits

        # Calculate check digit according to ISBN-13 algorithm
        # For ISBN-13, multiply alternating digits by 1 and 3, then mod 10
        total = 0
        for i, digit in enumerate(isbn_digits):
            if i % 2 == 0:
                total += digit
            else:
                total += 3 * digit

        check_digit = (10 - (total % 10)) % 10

        # Add check digit to the end
        isbn_digits.append(check_digit)

        # Format the ISBN with hyphens (optional)
        # Standard format is prefix-group-publisher-title-check
        # But we'll just return the 13 digits for simplicity
        return "".join(str(digit) for digit in isbn_digits)

    def jstor(self) -> str:
        """Generate a random JSTOR identifier.

        JSTOR IDs typically consist of a stable portion followed by a numeric identifier.
        """
        # JSTOR IDs often contain a numeric part
        numeric_id_length = self.random_int(6, 8)
        numeric_id = self.numerify("#"*numeric_id_length)

        # Sometimes they include a journal code or other prefix
        journal_codes = ["j", "i", "a", "p", "stable"]
        prefix = self.random_element(journal_codes)

        # Combine to form the JSTOR ID
        if prefix == "stable":
            jstor_id = f"{prefix}/{numeric_id}"
        else:
            jstor_id = f"{prefix}.{numeric_id}"

        return jstor_id

    def mag(self) -> str:
        """Generate a random Microsoft Academic Graph (MAG) identifier.

        Args:
            entity_type (str, optional): Type of entity for which to generate an ID.
                Options: "paper", "author", "journal", "conference", "field", "institution", or None.
                If None, a random type will be selected.

        """
        # Some entity types
        entity_type = self.random_element(
                ["paper", "author", "journal", "conference", "field", "institution"])

        # Generate appropriate ID based on entity type
        # MAG IDs are typically numeric and of varying lengths based on entity type
        if entity_type == "paper":
            # Paper IDs are usually 8-9 digits
            id_length = self.random_int(8, 9)
        elif entity_type == "author":
            # Author IDs are usually 7-8 digits
            id_length = self.random_int(7, 8)
        elif entity_type in ["journal", "conference"]:
            # Journal/Conference IDs are usually 5-7 digits
            id_length = self.random_int(5, 7)
        elif entity_type == "field":
            # Field IDs are usually 5-6 digits
            id_length = self.random_int(5, 6)
        elif entity_type == "institution":
            # Institution IDs are usually 6-7 digits
            id_length = self.random_int(6, 7)

        return self.numerify("#"*id_length)
