import random

from faker.providers import BaseProvider


class ExtIDProvider(BaseProvider):
    def issn(self) -> str:
        """
        Generate a random ISSN (International Standard Serial Number).

        An ISSN is an 8-digit code used to identify periodical publications.
        Format: XXXX-XXXX where the last digit is a check digit (0-9 or X).

        This function was generated by Claude.

        See also: https://www.loc.gov/issn/basics/basics-checkdigit.html
        """
        digits = [random.randint(0, 9) for _ in range(7)]

        # Calculate the check digit
        # Each digit is multiplied by its position (8 to 2)
        # Sum the products and calculate the remainder when divided by 11
        weights = range(8, 1, -1)
        checksum = sum(d * w for d, w in zip(digits, weights)) % 11

        # The check digit is 11 minus the remainder (or 0 if remainder is 0)
        # If the result is 10, it's represented as 'X'
        check_digit = 11 - checksum
        if check_digit == 11:
            check_digit = 0
        elif check_digit == 10:
            check_digit = 'X'

        # Format the ISSN as XXXX-XXXX
        issn_first_part = ''.join(str(d) for d in digits[:4])
        issn_second_part = ''.join(str(d) for d in digits[4:]) + str(check_digit)

        return f"{issn_first_part}-{issn_second_part}"

    def wikidata_qid(self) -> str:
        """
        Generate a random Wikidata QID; eg: Q42, Q1, Q12345678
        """
        qid = random.randint(1, 100000000)
        return f"Q{qid}"
