from datetime import datetime
from typing import Callable
import json
import random
import zoneinfo

import factory
from django.contrib.auth.hashers import (
    make_password,
)
from django.contrib.auth.models import User
from django.test import TestCase
from factory.django import DjangoModelFactory
from ninja.testing import TestClient
from ninja_apikey.models import APIKey

from djscholar.fcapi.models import Container, Release, Work
from djscholar.fcapi.views import v2api, ContainerSchema, BulkContainerSchema

client = TestClient(v2api)

def random_issn() -> str:
    """
    Generate a random ISSN (International Standard Serial Number).

    An ISSN is an 8-digit code used to identify periodical publications.
    Format: XXXX-XXXX where the last digit is a check digit (0-9 or X).

    This function was generated by Claude.

    See also: https://www.loc.gov/issn/basics/basics-checkdigit.html

    Returns:
        str: A randomly generated ISSN in the format "XXXX-XXXX"
    """
    digits = [random.randint(0, 9) for _ in range(7)]

    # Calculate the check digit
    # Each digit is multiplied by its position (8 to 2)
    # Sum the products and calculate the remainder when divided by 11
    weights = range(8, 1, -1)
    checksum = sum(d * w for d, w in zip(digits, weights)) % 11

    # The check digit is 11 minus the remainder (or 0 if remainder is 0)
    # If the result is 10, it's represented as 'X'
    check_digit = 11 - checksum
    if check_digit == 11:
        check_digit = 0
    elif check_digit == 10:
        check_digit = 'X'

    # Format the ISSN as XXXX-XXXX
    issn_first_part = ''.join(str(d) for d in digits[:4])
    issn_second_part = ''.join(str(d) for d in digits[4:]) + str(check_digit)

    return f"{issn_first_part}-{issn_second_part}"

def random_wikidata_qid() -> str:
    """
    Generate a random Wikidata QID.

    Wikidata QIDs follow the format Q followed by a number without leading zeros.
    While new QIDs are typically assigned sequentially, this function generates a random one
    that follows the same pattern.

    Valid examples: Q42, Q1, Q12345678

    This function was generated by Claude.

    Returns:
        str: A randomly generated Wikidata QID in the format "Q{number}"
    """
    # Generate a random number between 1 and 100000000 (arbitrary upper limit)
    # Real Wikidata has items in the millions, but the format supports higher numbers
    qid_number = random.randint(1, 100000000)

    return f"Q{qid_number}"

def lazy(generate: Callable) -> factory.LazyAttribute:
    return factory.LazyAttribute(lambda _: generate())

class ContainerFactory(DjangoModelFactory):
    issnl = lazy(random_issn)
    issne = lazy(random_issn)
    issnp = lazy(random_issn)
    wikidata_qid = lazy(random_wikidata_qid)
    updated = lazy(lambda: datetime.now(zoneinfo.ZoneInfo("UTC")))
    created = lazy(lambda: datetime.now(zoneinfo.ZoneInfo("UTC")))

    class Meta:
        model = Container


class ReleaseFactory(DjangoModelFactory):
    class Meta:
        model = Release


class WorkFactory(DjangoModelFactory):
    class Meta:
        model = Work


class UserFactory(DjangoModelFactory):
    class Meta:
        model = User


class APIKeyFactory(DjangoModelFactory):
    class Meta:
        model = APIKey


class TestContainerRoutes(TestCase):
    def setUp(self):
        user = User.objects.create_user(username="test", password="test")
        prefix = "prefix"
        key = "test_api_key"
        encoded = make_password(key)
        APIKey.objects.create(user=user, prefix=prefix, hashed_key=encoded)
        self.auth_headers = {"X-API-Key": f"{prefix}.{key}"}
        self.c = ContainerFactory.create()

    def test_get(self):
        response = client.get(f"/container/{self.c.id}")
        self.assertEqual(response.status_code, 200)

    def test_lookup(self):
        issnl = "1111-2222"
        response = client.get(f"/container/lookup?id_type=issnl&id_value={issnl}")
        self.assertEqual(response.status_code, 404)

        keys = [("wikidata_qid", self.c.wikidata_qid),
                ("issnl", self.c.issnl),
                ("issne", self.c.issne),
                ("issnp", self.c.issnp),
                ]

        for id_type, id_value in keys:
            response = client.get(f"/container/lookup?id_type={id_type}&id_value={id_value}")
            self.assertEqual(response.status_code, 200)
            self.assertEqual(response.data['id'], str(self.c.id))

    def test_get_releases(self):
        c = ContainerFactory.create()
        response = client.get(f"/container/{c.id}/releases")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(len(response.data), 0)

        rs = []
        for _ in range(4):
            r = ReleaseFactory.build()
            r.container = self.c
            r.work = WorkFactory.create()
            r.save()
            rs.append(r)

        response = client.get(f"/container/{self.c.id}/releases")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(len(response.data), len(rs))
        self.assertSetEqual(set([d['id'] for d in response.data]), set([str(r.id) for r in rs]))

    def test_create(self):
        c = ContainerFactory.build()
        data = ContainerSchema.from_orm(c).model_dump_json()
        response = client.post("/container", data=data, headers=self.auth_headers)
        self.assertEqual(response.status_code, 201)

        cs = Container.objects.filter(id=c.id)
        self.assertEqual(len(cs), 1)

        response = client.post("/container", data=data, headers=self.auth_headers)
        self.assertEqual(response.status_code, 400)

    def test_batch_create(self):
        cs = [ContainerSchema.from_orm(ContainerFactory.build()) for _ in range(100)]
        data = "["+",".join([c.model_dump_json() for c in cs])+"]"

        response = client.post("/containers", data=data, headers=self.auth_headers)
        self.assertEqual(response.status_code, 201)

        for c in cs:
            cs = Container.objects.filter(id=c.id)
            self.assertEqual(len(cs), 1)

    def test_update(self):
        # TODO
        pass

    def test_delete(self):
        unsaved = ContainerFactory.build()
        response = client.delete(f"/container/{unsaved.id}")
        self.assertEqual(response.status_code, 401)

        response = client.delete(f"/container/{unsaved.id}", headers=self.auth_headers)
        self.assertEqual(response.status_code, 404)

        response = client.delete(f"/container/{self.c.id}", headers=self.auth_headers)
        self.assertEqual(response.status_code, 200)

        response = client.delete(f"/container/{self.c.id}", headers=self.auth_headers)
        self.assertEqual(response.status_code, 404)
